# This action will be executed when a tag is created and uploaded.
# More information: https://github.com/davidcopano/github-actions-docs

name: Generate Android APK and publish release on Github

on: [push]

jobs:
  prepare_tools:
    name: Prepare tools to generate the APK
    runs-on: ubuntu-latest
    steps:
      - name: Get code from the current repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Convert Windows line endings to Linux from the gradlew file
        run: sudo apt update && sudo apt install dos2unix && cd android && dos2unix ./gradlew && cd ..

      - name: Make ./gradlew command executable
        run: cd android && chmod +x ./gradlew && cd ..

      - name: Build Ionic assets
        run: ionic build --prod

      - name: Copy generated assets from Ionic to Capacitor Android platform
        run: npx cap copy android && npx cap update android

      - name: Generate APK
        run: cd android && ./gradlew assembleRelease && cd ..

      # IMPORTANT: To sign the APK, you must add these secrets in the Settings -> Secrets section of the Github repo.
      # More info: https://github.com/r0adkll/sign-android-release
